# Change these first
owner: ReigenbornDavid # Your GitHub organization or username, where this repository lives
repo: galeno-status # The name of this repository

sites:
  - name: AKS Test
    url: http://apiTest.e-galeno.com.ar/api/monitorservicios/Monitor/aks
  - name: Galeno Test
    url: http://apiTest.e-galeno.com.ar/api/monitorservicios/Monitor/galeno
  - name: AKS
    url: https://salud-api.galeno.com.ar/salud/api/monitorservicios/Monitor/aks
    expectedStatusCodes:
      - 200    
  - name: Galeno
    url: https://salud-api.galeno.com.ar/salud/api/monitorservicios/Monitor/galeno
    expectedStatusCodes:
      - 200    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /galeno-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
